### ISSUE TITLE
BUG: 过期啦！

### ISSUE THREAD

**Issue by yjcxgjmtd** [A-kirami/nonebot-plugin-template#7]
### 确认事项

- [x] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认问题依旧存在。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的问题。

### 影响版本

最新版

### 问题描述

照片可以解析下来，但是视频发送的时候报错

### 复现步骤

nb run
发送一个链接
能解析照片
视频不能发送过来

### 预期行为

照片与视频共同发送

### 日志信息

 Running Matcher(type='message', module=nonebot-plugin-resolver, lineno=45) failed.
Traceback (most recent call last):
  File "E:\SparkPixel-Bot\None_bot\SPBot\.venv\Lib\site-packages\nonebot-plugin-resolver\__init__.py", line 457, in upload_group_file
    await bot.upload_group_file(group_id=group_id, file=file, name="{:.0f}.mp4".format(time.time()))
  File "E:\SparkPixel-Bot\None_bot\SPBot\.venv\Lib\site-packages\nonebot\internal\adapter\bot.py", line 122, in call_api
    raise exception
  File "E:\SparkPixel-Bot\None_bot\SPBot\.venv\Lib\site-packages\nonebot\internal\adapter\bot.py", line 97, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "E:\SparkPixel-Bot\None_bot\SPBot\.venv\Lib\site-packages\nonebot\adapters\onebot\v11\adapter.py", line 147, in _call_api
    return handle_api_result(await self._result_store.fetch(seq, timeout))
  File "E:\SparkPixel-Bot\None_bot\SPBot\.venv\Lib\site-packages\nonebot\adapters\onebot\v11\utils.py", line 58, in handle_api_result
    raise ActionFailed(**result)
nonebot.adapters.onebot.v11.exception.ActionFailed: ActionFailed(status='failed', retcode=200, data=None, echo='3')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 21, in <module>
  File "E:\SparkPixel-Bot\None_bot\SPBot\.venv\Lib\site-packages\nonebot\__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "E:\SparkPixel-Bot\None_bot\SPBot\.venv\Lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
    uvicorn.run(
  File "E:\SparkPixel-Bot\None_bot\SPBot\.venv\Lib\site-packages\uvicorn\main.py", line 577, in run
    server.run()
  File "E:\SparkPixel-Bot\None_bot\SPBot\.venv\Lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 637, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 604, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "E:\SparkPixel-Bot\None_bot\SPBot\.venv\Lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "E:\SparkPixel-Bot\None_bot\SPBot\.venv\Lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "E:\SparkPixel-Bot\None_bot\SPBot\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "E:\SparkPixel-Bot\None_bot\SPBot\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 825, in simple_run
    await handler(
  File "E:\SparkPixel-Bot\None_bot\SPBot\.venv\Lib\site-packages\nonebot\dependencies\__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "E:\SparkPixel-Bot\None_bot\SPBot\.venv\Lib\site-packages\nonebot-plugin-resolver\__init__.py", line 138, in bilibili
    await auto_video_send(event, f"{path}-res.mp4", IS_LAGRANGE)
  File "E:\SparkPixel-Bot\None_bot\SPBot\.venv\Lib\site-packages\nonebot-plugin-resolver\__init__.py", line 491, in auto_video_send
    await upload_data_file(bot=bot, event=event, data=data) if is_lagrange else bot.send(event, Message(MessageSegment.video(data)))
  File "E:\SparkPixel-Bot\None_bot\SPBot\.venv\Lib\site-packages\nonebot-plugin-resolver\__init__.py", line 451, in upload_data_file
    await upload_group_file(bot, group_id=event.group_id, file=data)
  File "E:\SparkPixel-Bot\None_bot\SPBot\.venv\Lib\site-packages\nonebot-plugin-resolver\__init__.py", line 460, in upload_group_file
    if isinstance(e, ActionFailed) and e.info["wording"] == "server" \
KeyError: 'wording'

### 参与贡献

- [ ] 我有足够的时间和能力，愿意为此提交 PR 来修复问题。

**Comment by A-kirami** [comment]
该仓库仅为模板库，并没有实际功能。
根据你提供的日志，应该是nonebot-plugin-resolver插件，仓库地址为：https://github.com/zhiyu1998/nonebot-plugin-resolver
