### ISSUE TITLE
BUG: [ERROR] nonebot | Running Matcher(type='message', module=nonebot-plugin-resolver, lineno=46) failed.

### ISSUE THREAD

**Issue by Littlekunlun** [A-kirami/nonebot-plugin-template#8]
### 确认事项

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认问题依旧存在。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的问题。

### 影响版本

1.1.0

### 问题描述

视频下载到了对应目录，但是不会发出来也不会自动删除

### 复现步骤

发送视频后可以正确的返回解析信息，但是在后台会出现错误

### 日志信息

06-23 01:33:37 [ERROR] nonebot | Running Matcher(type='message', module=nonebot-plugin-resolver, lineno=46) failed.
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "C:\Users\Administrator\Desktop\BOT\xiaokunlun\.venv\Lib\site-packages\nonebot\__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\BOT\xiaokunlun\.venv\Lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
    uvicorn.run(
  File "C:\Users\Administrator\Desktop\BOT\xiaokunlun\.venv\Lib\site-packages\uvicorn\main.py", line 577, in run
    server.run()
  File "C:\Users\Administrator\Desktop\BOT\xiaokunlun\.venv\Lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 322, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 641, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1987, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\Desktop\BOT\xiaokunlun\.venv\Lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "C:\Users\Administrator\Desktop\BOT\xiaokunlun\.venv\Lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\Desktop\BOT\xiaokunlun\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\Desktop\BOT\xiaokunlun\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 825, in simple_run
    await handler(
  File "C:\Users\Administrator\Desktop\BOT\xiaokunlun\.venv\Lib\site-packages\nonebot\dependencies\__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\Administrator\Desktop\BOT\xiaokunlun\.venv\Lib\site-packages\nonebot-plugin-resolver\__init__.py", line 134, in bilibili
    video_url, audio_url = getDownloadUrl(url)
  File "C:\Users\Administrator\Desktop\BOT\xiaokunlun\.venv\Lib\site-packages\nonebot-plugin-resolver\bili23_utils.py", line 24, in getDownloadUrl
    info = re.search(r"<script>window\.__playinfo__=({.*})<\/script><script>", resp.text)[1]
TypeError: 'NoneType' object is not subscriptable

### 参与贡献

- [ ] 我有足够的时间和能力，愿意为此提交 PR 来修复问题。

**Comment by Littlekunlun** [comment]
打扰了，问题已解决，需要拉格朗日处于打开状态
